version: "3"
services:
  emqx1:
    image: emqx/emqx:5.8.0
    container_name: mqtt
    restart: always
    networks:
      - default
    volumes:
      - /Users/wuchaoqiu/Documents/docker-data/emqx/data:/opt/emqx/data
      - /Users/wuchaoqiu/Documents/docker-data/emqx/log:/opt/emqx/log
    ports:
      # tcp, mqtt
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      # Dashbaord port, use http://localhost:18083 to visit, default user/pwd -> admin/public
      - 18083:18083     
networks:
    default:
        external: true 
        name: docker-data_default    
